using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Briefcase.Domain.Entities;
using Briefcase.Domain.Interfaces;
using Briefcase.Infrastructure.Persistence;

namespace Briefcase.ApiService.Controllers;

/// <summary>
/// Serves one-time share links generated by the transfer flow.
/// No authentication required — the slug is the access credential.
/// </summary>
[ApiController]
[Route("api/share")]
public class ShareController(AppDbContext db, IFileStorageService storage, IMemoryCache cache, IEncryptionService encryption) : ControllerBase
{
    // GET /api/share/{slug}  →  retrieve shared message content (marks one-time links as used)
    [HttpGet("{slug}")]
    public async Task<IActionResult> GetSharedMessage(string slug, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(slug) || slug.Length > 64)
            return BadRequest();

        var shareLink = await db.ShareLinks
            .Include(s => s.Message)
                .ThenInclude(m => m.FileAttachment)
            .FirstOrDefaultAsync(s => s.Slug == slug, ct);

        if (shareLink is null || shareLink.RevokedAt.HasValue)
            return NotFound();

        if (shareLink.ExpiresAt.HasValue && shareLink.ExpiresAt < DateTime.UtcNow)
            return NotFound();

        var message = shareLink.Message;
        if (message.IsDeleted)
            return NotFound();

        // For file messages, generate short-lived one-time tokens so the client
        // can download/preview without authentication and without re-using the slug.
        string? fileDownloadToken = null;
        string? filePreviewToken = null;
        if (message.Kind == MessageKind.File && message.FileAttachment is not null)
        {
            fileDownloadToken = Guid.NewGuid().ToString("N");
            cache.Set($"dt:{fileDownloadToken}", message.FileAttachment.Id, TimeSpan.FromMinutes(15));

            if (!string.IsNullOrWhiteSpace(message.FileAttachment.PreviewBlobPath))
            {
                filePreviewToken = Guid.NewGuid().ToString("N");
                cache.Set($"pt:{filePreviewToken}", message.FileAttachment.Id, TimeSpan.FromMinutes(15));
            }
        }

        // Revoke immediately if this is a one-time link
        if (shareLink.IsOneTime)
            shareLink.RevokedAt = DateTime.UtcNow;

        shareLink.ViewCount++;
        await db.SaveChangesAsync(ct);

        return Ok(new SharedMessageDto(
            message.Id,
            message.Kind.ToString(),
            message.Content,
            message.FileId,
            message.FileAttachment?.OriginalName,
            filePreviewToken,
            message.CreatedAt,
            fileDownloadToken));
    }

    // GET /api/share/{slug}/file?token={token}  →  one-time anonymous file download
    [HttpGet("{slug}/file")]
    public async Task<IActionResult> DownloadFile(string slug, [FromQuery] string token, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(token))
            return BadRequest();

        if (!cache.TryGetValue($"dt:{token}", out Guid fileId))
            return NotFound();

        cache.Remove($"dt:{token}"); // one-time use

        var attachment = await db.FileAttachments
            .FirstOrDefaultAsync(f => f.Id == fileId, ct);

        if (attachment is null)
            return NotFound();

        var stream = await storage.DownloadAsync(attachment.BlobPath, ct);
        if (attachment.IsEncrypted || encryption.IsEnabled)
        {
            var decryptedMs = new MemoryStream();
            await encryption.DecryptStreamAsync(stream, decryptedMs, ct);
            await stream.DisposeAsync();
            decryptedMs.Position = 0;
            return File(decryptedMs, attachment.ContentType, attachment.OriginalName);
        }
        return File(stream, attachment.ContentType, attachment.OriginalName);
    }

    // GET /api/share/{slug}/preview?token={token}  →  anonymous preview image
    [HttpGet("{slug}/preview")]
    public async Task<IActionResult> GetPreview(string slug, [FromQuery] string token, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(token))
            return BadRequest();

        if (!cache.TryGetValue($"pt:{token}", out Guid fileId))
            return NotFound();

        var attachment = await db.FileAttachments
            .FirstOrDefaultAsync(f => f.Id == fileId, ct);

        if (attachment is null || string.IsNullOrWhiteSpace(attachment.PreviewBlobPath))
            return NotFound();

        var stream = await storage.DownloadAsync(attachment.PreviewBlobPath, ct);
        if (attachment.IsEncrypted || encryption.IsEnabled)
        {
            var decryptedMs = new MemoryStream();
            await encryption.DecryptStreamAsync(stream, decryptedMs, ct);
            await stream.DisposeAsync();
            decryptedMs.Position = 0;
            return File(decryptedMs, "image/jpeg");
        }
        return File(stream, "image/jpeg");
    }
}

public record SharedMessageDto(
    Guid MessageId,
    string Kind,
    string? Content,
    Guid? FileId,
    string? FileName,
    string? FilePreviewToken,
    DateTime CreatedAt,
    string? FileDownloadToken);
